"""Add lead status management fields and history table

Revision ID: 5fc83713bf35
Revises: af665e05c851
Create Date: 2026-06-22 09:30:12.689244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc83713bf35'
down_revision: Union[str, Sequence[str], None] = 'af665e05c851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('status_notes', sa.Text(), nullable=True))
    op.add_column('leads', sa.Column('last_contacted', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'leads', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'last_contacted')
    op.drop_column('leads', 'status_notes')
    op.drop_column('leads', 'assigned_to_id')
    # ### end Alembic commands ###
