"""Add notifications table for hot lead alerts

Revision ID: 6d70eebd0c1e
Revises: 5fc83713bf35
Create Date: 2026-06-22 09:53:11.505522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d70eebd0c1e'
down_revision: Union[str, Sequence[str], None] = '5fc83713bf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
