"""Add score history table for tracking score changes

Revision ID: 835aab60e49f
Revises: 6d70eebd0c1e
Create Date: 2026-06-22 13:11:06.468369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835aab60e49f'
down_revision: Union[str, Sequence[str], None] = '6d70eebd0c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
